---
extends:
  - eslint:recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:react/recommended
  - prettier

parser: babel-eslint

parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    modules: true

env:
  browser: true
  node: true

rules:
  # Use TypeScript instead
  react/prop-types: 0
  # Readable code is my primary concern
  react/no-unescaped-entities: 0

settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    typescript:
      alwaysTryTypes: true
  react:
    version: detect
